services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_db_mongoose
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    restart: unless-stopped

volumes:
  mongo_data: